# Generated by Django 4.2.3 on 2023-08-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='video',
            field=models.FileField(null=True, upload_to='post_videos/', verbose_name='Video'),
        ),
    ]
