# Generated by Django 4.2.3 on 2023-08-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
